### PR TITLE
Fix client_id and client_secret parameter names

### PR DESCRIPTION
**Pull request by vbedegi**
Form parameter names should use underscores instead of hyphens

### CODE REVIEW

**Comment by weavejester** [comment]
Can you squash your commits?

**Comment by vbedegi** [comment]
Done

**Comment by weavejester** [comment]
It doesn't look like the commits were squashed.

**Comment by weavejester** [comment]
Maybe I should fix this manually. It looks like the commit history is just getting worse :)

**Comment by weavejester** [comment]
Merged manually.

**Comment by vbedegi** [comment]
Yeah, thanks! I made a git disaster here.

**Pull request closed without merging**
