### PR TITLE
Added missing `handler` parameter to example in README.md

### LINKED ISSUE #32: Is the example `ring-defaults` missing the actual handler in README.md?
Hiya - I might be being dumb, but in README.md it states:
```
(wrap-defaults (-> site-defaults (assoc-in [:session :cookie-attrs :same-site] :lax)))
```

Isn't this missing the actual handler itself as the first parameter to `wrap-defaults`:
```
(wrap-defaults YOUR-ACTUAL-HANDLER (-> site-defaults (assoc-in [:session :cookie-attrs :same-site] :lax)))
```

(I realise this is probably used with `(-> YOUR-ACTUAL-HANDLER (wrap-defaults (-> ....` but it tripped me up :-))

Happy to do a PR with updated doc?

### PR DESCRIPTION
**Pull request by yatesco**
Fixes #32

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks. Can you change the commit message to:

    Fix missing argument in README example

**Comment by yatesco** [comment]
Happy to … er, how? Do I git amend and push —force? There must be a more elegant way :-)

**Comment by weavejester** [comment]
If there is a more elegant way, I don't know it. I always just amend and force push 😃

**Comment by yatesco** [comment]
Done :-).

**Pull request merged**
