### PR TITLE
Covers edge case of parametrised authorize-uri

### PR DESCRIPTION
**Pull request by Otann**
Sometimes `authorization-uri` may contain additional parameters, like:

    https://identity.company.com/oauth2/authorize?business_partner_id=XXXX

In this case appending ? would break the URL, but checking should help.

### CODE REVIEW

**Comment by weavejester** [comment]
Looks like the tests are failing, and the commit needs new tests to check the new functionality.

**Comment by Otann** [comment]
@weavejester fixed the build and added a new test

**Comment by weavejester** [comment]
Thanks, could you squash your commits and change `Covers` to `Cover` in your commit message?

**Comment by Otann** [comment]
@weavejester done!

**Comment by weavejester** [comment]
Great! I've looked the code over and it all looks okay, but I think you could add a `^String` type hint after `.contains` to avoid reflection. Once you add that, it should be fine to merge.

**Comment by Otann** [comment]
done that too!

**Comment by weavejester** [comment]
Thanks! I'm just about to merge. Can you fix the spelling of "parametrised" to "parameterized" in the commit message?

**Comment by Otann** [comment]
that too )

**Pull request merged**
